### ISSUE TITLE
installation failed in editable mode

### ISSUE THREAD

**Issue by sarahsweet** [lukaswenzl/astrometry#6]
When installing astrometry, I get:

`$ pip install -e /Users/ssweet/
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /Users/ssweet`

I am running macOS Mojave 10.14.6.

I can run 

`$ python astrometry.py sample_images/sample_file.fits`, which calculates the correct WCS and produces sample_file_astro.fits. It does not open or write the plots.

**Comment by lukaswenzl** [comment]
Hi Sarah,
When installing in the editable mode you need to specify the path to the folder where the GitHub repository is located. You seem to have specified your home user folder here that is why the setup.py is not found. 
One simple way to do this is to go to where you cloned the GitHub repo then.
`cd astrometry`
this brings you into the folder.
then install with pip using
`pip install -e .`

Depending on your setup it could be that the plots can not open. You can tell the code to save the plots with the following flag: "  --save_images True"

**Comment by sarahsweet** [comment]
Hi Lukas,
Thanks - apologies I'd missed that step. The plots still do not open but the flag you've provided works fine to save the plots.
