### ISSUE TITLE
About incorrect offsets 

### ISSUE THREAD

**Issue by Sullofect** [lukaswenzl/astrometry#7]
I was trying to offset an MUSE white light image to Gaia but encounter weird offset results. Basically, I provide my image and use Gaia (both use query and my own Gaia catalog) for position reference. The Result diagnosis figure shows that they are matched perfectly, but when I open the .fits file in DS9 and overplot with Gaia targets, these Gaia targets are completely off from the centroids of the objects.

**Comment by lukaswenzl** [comment]
Hi there, thanks for reaching out.  If the shown figure appears to show a good astrometry fit, I think the first thing to check would be if the new astrometry info gets correctly saved. The code creates a new file with the updated astrometry.

Can you confirm that you are using that new file and that the position information has changed compared to your original file?

Beyond that I would need some more information to help. I am happy to give it a try on my end in case you can share an example file with me

**Comment by lukaswenzl** [comment]
Thanks for sending your example file. 
This uncovered a small bug in the fine transformation:
Rotational corrections where applied backwards which led to lower scores and the fine transformation being discarded.
Will fix this which should improve overall accuracy.

**Comment by lukaswenzl** [comment]
#8 fixed with pull request

**Comment by lukaswenzl** [comment]
Turns out there is another bug. The fit isn't saved correctly so while the good shows an accurate solution there is an offset when opening the calibrated fits file in another software like ds9. Will investigate

**Comment by lukaswenzl** [comment]
I think I found the bug: there was an issue with indexing starting from 0 which caused offsets of 1 in both the x and y direction in the saved fits file. See: #9

**Comment by lukaswenzl** [comment]
Issue is now resolved so closing this
